image: docker:stable
services:
- docker:dind

stages:
- build
- deploy
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

build prod:
  image: node:10
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist
  only:
    - master

build dev:
  variables:
    NODE_ENV: develop
  image: node:10
  stage: build
  script:
    - npm ci
    - npm run build
    - mv dist dist_dev
  artifacts:
    expire_in: 1 week
    paths:
      - dist_dev
  only:
    - develop

deploy master to server:
  image: alpine
  stage: deploy
  before_script:
    - apk update
    - apk add --no-cache rsync openssh
    - echo "$SSH_PRIVATE_KEY" >> key.pem
    - chmod 400 key.pem
  script:
    - rsync -rav -O --no-perms -e "ssh -q -i key.pem -o 'StrictHostKeyChecking no'" dist/ neoin@104.248.247.60:/home/neoin/market.neoin.club/source/public
  only:
    - master

deploy develop to server:
  image: alpine
  stage: deploy
  before_script:
    - apk update
    - apk add --no-cache rsync openssh
    - echo "$SSH_PRIVATE_KEY" >> key.pem
    - chmod 400 key.pem
  script:
    - rsync -rav -O --no-perms -e "ssh -q -i key.pem -o 'StrictHostKeyChecking no'" dist_dev/ neoin@104.248.247.60:/home/neoin/market.beta.neoin.club/source/public
  only:
    - develop
